// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message/message.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LastMessagesRequest struct {
	UserIDs              []string `protobuf:"bytes,1,rep,name=userIDs,proto3" json:"userIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastMessagesRequest) Reset()         { *m = LastMessagesRequest{} }
func (m *LastMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*LastMessagesRequest) ProtoMessage()    {}
func (*LastMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f274517418484e40, []int{0}
}

func (m *LastMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastMessagesRequest.Unmarshal(m, b)
}
func (m *LastMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastMessagesRequest.Marshal(b, m, deterministic)
}
func (m *LastMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastMessagesRequest.Merge(m, src)
}
func (m *LastMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_LastMessagesRequest.Size(m)
}
func (m *LastMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LastMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LastMessagesRequest proto.InternalMessageInfo

func (m *LastMessagesRequest) GetUserIDs() []string {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

type LastMessagesResponse struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LastMessagesResponse) Reset()         { *m = LastMessagesResponse{} }
func (m *LastMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*LastMessagesResponse) ProtoMessage()    {}
func (*LastMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f274517418484e40, []int{1}
}

func (m *LastMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastMessagesResponse.Unmarshal(m, b)
}
func (m *LastMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastMessagesResponse.Marshal(b, m, deterministic)
}
func (m *LastMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastMessagesResponse.Merge(m, src)
}
func (m *LastMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_LastMessagesResponse.Size(m)
}
func (m *LastMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LastMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LastMessagesResponse proto.InternalMessageInfo

func (m *LastMessagesResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Message struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender               string   `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver             string   `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IsRead               bool     `protobuf:"varint,5,opt,name=isRead,proto3" json:"isRead,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_f274517418484e40, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Message) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetIsRead() bool {
	if m != nil {
		return m.IsRead
	}
	return false
}

func (m *Message) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type MessagesRequest struct {
	Milestone            int64    `protobuf:"varint,1,opt,name=milestone,proto3" json:"milestone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagesRequest) Reset()         { *m = MessagesRequest{} }
func (m *MessagesRequest) String() string { return proto.CompactTextString(m) }
func (*MessagesRequest) ProtoMessage()    {}
func (*MessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f274517418484e40, []int{3}
}

func (m *MessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesRequest.Unmarshal(m, b)
}
func (m *MessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesRequest.Marshal(b, m, deterministic)
}
func (m *MessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesRequest.Merge(m, src)
}
func (m *MessagesRequest) XXX_Size() int {
	return xxx_messageInfo_MessagesRequest.Size(m)
}
func (m *MessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesRequest proto.InternalMessageInfo

func (m *MessagesRequest) GetMilestone() int64 {
	if m != nil {
		return m.Milestone
	}
	return 0
}

type Messages struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Messages) Reset()         { *m = Messages{} }
func (m *Messages) String() string { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()    {}
func (*Messages) Descriptor() ([]byte, []int) {
	return fileDescriptor_f274517418484e40, []int{4}
}

func (m *Messages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Messages.Unmarshal(m, b)
}
func (m *Messages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Messages.Marshal(b, m, deterministic)
}
func (m *Messages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Messages.Merge(m, src)
}
func (m *Messages) XXX_Size() int {
	return xxx_messageInfo_Messages.Size(m)
}
func (m *Messages) XXX_DiscardUnknown() {
	xxx_messageInfo_Messages.DiscardUnknown(m)
}

var xxx_messageInfo_Messages proto.InternalMessageInfo

func (m *Messages) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f274517418484e40, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LastMessagesRequest)(nil), "message.LastMessagesRequest")
	proto.RegisterType((*LastMessagesResponse)(nil), "message.LastMessagesResponse")
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*MessagesRequest)(nil), "message.MessagesRequest")
	proto.RegisterType((*Messages)(nil), "message.Messages")
	proto.RegisterType((*Empty)(nil), "message.Empty")
}

func init() { proto.RegisterFile("proto/message/message.proto", fileDescriptor_f274517418484e40) }

var fileDescriptor_f274517418484e40 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcf, 0x4a, 0xf3, 0x40,
	0x10, 0xef, 0x36, 0x6d, 0x93, 0xcc, 0x07, 0xfd, 0xbe, 0x6f, 0x2a, 0xb2, 0xc4, 0x0a, 0x61, 0x4f,
	0x41, 0xa4, 0x85, 0x7a, 0xe9, 0x55, 0xa8, 0x07, 0x41, 0x2f, 0x5b, 0x5f, 0x20, 0x26, 0x83, 0x04,
	0x6c, 0x52, 0x77, 0xb7, 0x05, 0x1f, 0xc6, 0x37, 0xf2, 0xa1, 0xa4, 0x9b, 0x4d, 0xaa, 0xad, 0x1e,
	0x3c, 0x2d, 0xbf, 0x7f, 0xb3, 0xb3, 0xb3, 0x03, 0x67, 0x6b, 0x55, 0x99, 0x6a, 0xba, 0x22, 0xad,
	0xd3, 0x27, 0x6a, 0xce, 0x89, 0x65, 0xd1, 0x77, 0x50, 0x4c, 0x61, 0x74, 0x97, 0x6a, 0x73, 0x5f,
	0x43, 0x2d, 0xe9, 0x65, 0x43, 0xda, 0x20, 0x07, 0x7f, 0xa3, 0x49, 0xdd, 0x2e, 0x34, 0x67, 0xb1,
	0x97, 0x84, 0xb2, 0x81, 0x62, 0x01, 0x27, 0x5f, 0x03, 0x7a, 0x5d, 0x95, 0x9a, 0xf0, 0x12, 0x02,
	0x57, 0xb3, 0x8e, 0xfc, 0x99, 0xfd, 0x9b, 0x34, 0x77, 0x3a, 0xb3, 0x6c, 0x1d, 0xe2, 0x8d, 0x81,
	0xef, 0x58, 0x1c, 0x42, 0xb7, 0xc8, 0x39, 0x8b, 0x59, 0x12, 0xca, 0x6e, 0x91, 0xe3, 0x29, 0x0c,
	0x34, 0x95, 0x39, 0x29, 0xde, 0xb5, 0x9c, 0x43, 0x18, 0x41, 0xa0, 0x28, 0xa3, 0x62, 0x4b, 0x8a,
	0x7b, 0x56, 0x69, 0xf1, 0xae, 0xdf, 0xac, 0x2a, 0x0d, 0x95, 0x86, 0xf7, 0xac, 0xd4, 0xc0, 0x5d,
	0xb5, 0x42, 0x4b, 0x4a, 0x73, 0xde, 0x8f, 0x59, 0x12, 0x48, 0x87, 0x70, 0x0c, 0x61, 0xa6, 0x28,
	0x35, 0x94, 0x5f, 0x1b, 0x3e, 0x88, 0x59, 0xe2, 0xc9, 0x3d, 0x21, 0xa6, 0xf0, 0xf7, 0x70, 0x24,
	0x63, 0x08, 0x57, 0xc5, 0x33, 0x69, 0x53, 0x95, 0x64, 0xbb, 0xf5, 0xe4, 0x9e, 0x10, 0x73, 0x08,
	0x9a, 0xc0, 0x2f, 0x47, 0xe1, 0x43, 0xff, 0x66, 0xb5, 0x36, 0xaf, 0xb3, 0x77, 0x06, 0x43, 0x27,
	0x2f, 0x49, 0x6d, 0x8b, 0x8c, 0xf0, 0x02, 0x7a, 0x4b, 0x2a, 0x73, 0x3c, 0xca, 0x47, 0xc3, 0x96,
	0xb1, 0x61, 0xd1, 0xc1, 0x39, 0xf8, 0xb2, 0x1e, 0x07, 0xf2, 0x43, 0x7b, 0xf3, 0x88, 0xe8, 0xff,
	0x91, 0x22, 0x3a, 0xf8, 0x00, 0x23, 0x97, 0xfc, 0xfc, 0xb3, 0x38, 0x6e, 0xbd, 0xdf, 0x6c, 0x48,
	0x74, 0xfe, 0x83, 0x5a, 0xaf, 0x83, 0xe8, 0x3c, 0x0e, 0xec, 0xa6, 0x5d, 0x7d, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x12, 0x20, 0x5e, 0x2e, 0x88, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageServiceClient interface {
	Send(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error)
	Receive(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (*Messages, error)
	ReceiveLastMessages(ctx context.Context, in *LastMessagesRequest, opts ...grpc.CallOption) (*LastMessagesResponse, error)
}

type messageServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessageServiceClient(cc *grpc.ClientConn) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) Send(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/message.MessageService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) Receive(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (*Messages, error) {
	out := new(Messages)
	err := c.cc.Invoke(ctx, "/message.MessageService/Receive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) ReceiveLastMessages(ctx context.Context, in *LastMessagesRequest, opts ...grpc.CallOption) (*LastMessagesResponse, error) {
	out := new(LastMessagesResponse)
	err := c.cc.Invoke(ctx, "/message.MessageService/ReceiveLastMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
type MessageServiceServer interface {
	Send(context.Context, *Message) (*Empty, error)
	Receive(context.Context, *MessagesRequest) (*Messages, error)
	ReceiveLastMessages(context.Context, *LastMessagesRequest) (*LastMessagesResponse, error)
}

// UnimplementedMessageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (*UnimplementedMessageServiceServer) Send(ctx context.Context, req *Message) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedMessageServiceServer) Receive(ctx context.Context, req *MessagesRequest) (*Messages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Receive not implemented")
}
func (*UnimplementedMessageServiceServer) ReceiveLastMessages(ctx context.Context, req *LastMessagesRequest) (*LastMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveLastMessages not implemented")
}

func RegisterMessageServiceServer(s *grpc.Server, srv MessageServiceServer) {
	s.RegisterService(&_MessageService_serviceDesc, srv)
}

func _MessageService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Send(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Receive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/Receive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Receive(ctx, req.(*MessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_ReceiveLastMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).ReceiveLastMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/ReceiveLastMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).ReceiveLastMessages(ctx, req.(*LastMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _MessageService_Send_Handler,
		},
		{
			MethodName: "Receive",
			Handler:    _MessageService_Receive_Handler,
		},
		{
			MethodName: "ReceiveLastMessages",
			Handler:    _MessageService_ReceiveLastMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/message/message.proto",
}
